/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-06 12:30:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cliente_005fpasta;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import locadora303.Cliente;

public final class excluirCliente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("locadora303.Cliente");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt\" >\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"ISO-8859-1\">\r\n");
      out.write("  <title>Clientes</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"estilos/telaAtualizacao.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <section id=\"logRegForm\" class=\"logRegForm\"> \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-lg-7 col-md-10\">\r\n");
      out.write("        <div class=\"contact_form_wrappre2\">\r\n");
      out.write("        <h2>\r\n");
      out.write("                Excluir Cliente\r\n");
      out.write("        </h2>\r\n");
      out.write("            <label class=\"mensagem\" id=\"msg\"> \r\n");
      out.write("                ");

                    if(request.getParameter("pMensagem") != null)         
                        out.write(request.getParameter("pMensagem"));
                
      out.write("\r\n");
      out.write("            </label>\r\n");
      out.write("            \r\n");
      out.write("            ");

                String vCpfCliente = request.getParameter("cpfcliente");
                Cliente cli = new Cliente();
                cli.setCpfCliente(vCpfCliente);
                cli = cli.consultarCliente();
            
      out.write("\r\n");
      out.write("            <form action=\"excluirDadosCliente.jsp\" method=\"post\">\r\n");
      out.write("            <div class=\"inputArea\">\r\n");
      out.write("                \r\n");
      out.write("            <!-- CPF -->\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col\">  \r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input id=\"cpfcliente\" name=\"cpfcliente\" type=\"text\" class=\"form-control\" readonly=\"true\" value=\"");
out.write(vCpfCliente);
      out.write("\" aria-describedby=\"Site\" required maxlength=\"11\">\r\n");
      out.write("                        <div class=\"input-group-prepend\">\r\n");
      out.write("                            <span class=\"input-group-text\" id=\"Site\">\r\n");
      out.write("                                <i class=\"far fa-address-book\" style='font-size:24px'></i>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- NOME -->    \r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col\">   \r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input id=\"nomecliente\" name=\"nomecliente\" type=\"text\" class=\"form-control\" readonly=\"true\" value=\"");
out.write(cli.getNomeCliente());
      out.write("\" aria-describedby=\"url\" required maxlength=\"40\">\r\n");
      out.write("                        <div class=\"input-group-prepend\">\r\n");
      out.write("                            <span class=\"input-group-text\" id=\"url\">\r\n");
      out.write("                                <i class=\"far fa-address-card\" style='font-size:24px'></i>\r\n");
      out.write("                            </span> \r\n");
      out.write("                        </div>        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- FONE -->    \r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col\">   \r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" id=\"fonecliente\" name=\"fonecliente\" class=\"form-control\" readonly=\"true\" value=\"");
out.write(cli.getFoneCliente());
      out.write("\"  aria-describedby=\"url\" maxlength=\"15\">\r\n");
      out.write("                        <div class=\"input-group-prepend\">\r\n");
      out.write("                            <span class=\"input-group-text\" id=\"url\">\r\n");
      out.write("                                <i class=\"fas fa-phone\" style='font-size:24px'></i>\r\n");
      out.write("                            </span> \r\n");
      out.write("                        </div>        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>   \r\n");
      out.write("            \r\n");
      out.write("            <!-- EMAIL -->    \r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col\">   \r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" id=\"emailcliente\" name=\"emailcliente\" class=\"form-control\" readonly=\"true\" value=\"");
out.write(cli.getEmailCliente());
      out.write("\" aria-describedby=\"url\" maxlength=\"50\">\r\n");
      out.write("                        <div class=\"input-group-prepend\">\r\n");
      out.write("                            <span class=\"input-group-text\" id=\"url\">\r\n");
      out.write("                                <i class=\"far fa-envelope-open\" style='font-size:24px'></i>\r\n");
      out.write("                            </span> \r\n");
      out.write("                        </div>        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> \r\n");
      out.write("             \r\n");
      out.write("            <!-- NR CARTÃO DEB CRED -->    \r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col\">   \r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" id=\"nrcartaodebcred\" name=\"nrcartaodebcred\"  class=\"form-control\" readonly=\"true\" value=\"");
out.write(cli.getNrCartaoDebCred());
      out.write("\" aria-describedby=\"url\" maxlength=\"16\">\r\n");
      out.write("                        <div class=\"input-group-prepend\">\r\n");
      out.write("                            <span class=\"input-group-text\" id=\"url\">\r\n");
      out.write("                                <i class=\"fas fa-money-check-alt\" style='font-size:24px'></i>\r\n");
      out.write("                            </span> \r\n");
      out.write("                        </div>        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> \r\n");
      out.write("            \r\n");
      out.write("             <!-- CHAVE PIX -->    \r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col\">   \r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" id=\"chavepix\" name=\"chavepix\" class=\"form-control\" readonly=\"true\" value=\"");
out.write(cli.getChavePix());
      out.write("\" aria-describedby=\"url\" maxlength=\"60\">\r\n");
      out.write("                        <div class=\"input-group-prepend\">\r\n");
      out.write("                            <span class=\"input-group-text\" id=\"url\">\r\n");
      out.write("                                <i class=\"fas fa-money-bill-wave-alt\" style='font-size:24px'></i>\r\n");
      out.write("                            </span> \r\n");
      out.write("                        </div>        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> \r\n");
      out.write("            \r\n");
      out.write("            <!-- BOTOES -->\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <button class=\"loginnow\" type=\"submit\">Excluir</button><br>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
